# See
# - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
# - https://github.com/argoproj/argo-cd/blob/v2.2.5/docs/operator-manual/argocd-cmd-params-cm.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.basehref: "/argocd"

  # Run Argo CD Server without TLS. We do this because Istio handles TLS
  # termination and mutual TLS among mesh services.
  server.insecure: "true"

  # Disable client authentication
  server.disable.auth: "true"

  # Set the log level to one of: debug|info|warn|error.
  server.log.level: "debug"

