apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: monitoring

resources:
- pushgateway.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.18.2-patch/samples/addons/prometheus.yaml
