
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 9091
  selector:
    app: pushgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
