
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: istio-system
spec:
  selector:
    app: pushgateway
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 31500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
