apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Other Calico configuration options...
  # ...
  calico_backend: "bird"
  iptablesBackend: "Legacy"
  veth_mtu: "1400"
  cni_network_config: |
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "k8s-node-name",
          "mtu": 1500
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
