apiVersion: v1
kind: Service
metadata:
  labels:
    app: landingpage
  name: landingpage
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: landingpage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: landingpage
  name: landingpage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
        - image: "karikolehmainen/dsil-landing:0.2"
          imagePullPolicy: Always
          name: landingpage
          ports:
          - containerPort: 80
            name: http
