---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgCXyPdWwHC47PpNYr3NYD107j2sLWT7CRaEarL0zs4xcPf2CvrZnObbt3ZDre7Z3dOV2/rokSvbTCF38IjmKKV3Pd3qt9rZ/wlzrsKDDXI2XSikIg7NksGlbuvMynZc9mHjLdapeutFcCwrv5XIVVTrW/GvlNKwltojwD3PRXKPzyYrmCUmimxm+4OFf0osYcz7v6B3pHTuHzDH5qseTyqbD7e7i2yY3e/ufIhf42Xl4bAtO1/jt5rVbdA6LxK3WEOTG8fQ4FBjnTDqF1RGF3DB55D3BoYrB9/b54ysd/x8Vvoxv2sJb4Sn/ZFNoxpvMTl+9U/VN54j+Yw9eilVyUUmwPetC4fF7b9uNXVb/7YhSKcHMqZoC7Y7ub5EJHmzI05aA/EDWIanJPV+aVccnUumxxe3dE5pDi0dDxw0cvh4H8IFe1A+oy4gKOKnjWgsVHnyN7N4G6Fcf6nnGlhJoMJo462+s8fix2/Fv0d66hdqraGgQnKUosf+kSzqChL/3POXZV3NMrScsveNnBuD9hFdI0YFA3MfgawFiLwuBk02MgmwXbCUiekXfxX5lYX6abTG157VtkKL47yxjdoJwR+OB175k1EsDtDbpoSQIvST/X2Tq52//ju4arvrGwPp1gHpQNwZlnW/rqwbdwFTkU6QauMFmwaXudJ4cGPBCNr3v8j3yJc4HHyrfOtPbKWd0l/iuDk0pgAE6OdkDo+7UpKRcoHrhotV7w4fq2M=
    username: AgAc+yFmAQDtlvyoncKv+t6tXrOA1+wc9rjh2GV4w82oN576fGSNq4zpHcI5tTpnaq/Q1yV4Q99SNVin8xEC9zBXiZNhPiarLPTiWd8XTOPN+/SfSNWp5FKxjQNP1taDRDCaG4hOIS9139MrkkYLcYZ/t3U9kZwDp2dPO4xcRHYHS1jIG0HOx5iwrS4tpu4ev4E98Dn9eLL6p/iGcbxVIGclR+AdeCe0U2dt5OlsTEvFetFU/DSKGt+eara3MkgBw58k0AMnkWjN0L6jGZ99N8mBWiIIWWCwJR43k0fBJM1ByWyswHCNxORv+nrOTrdvdhVLsy0rluqg+S/A4FPIn28L64n7dd/ZTneHS3Exa10VVLHaZcY4AmIx7Qw52GMwQxLtqHnxU6IwQqQCRlCwvABDG6goK+T70VqgBUOmOY2/uk2E3lLvfWfj6QN+T+pEbqj9lqvhnLzwi8gWFi0xmztGuMqLfQ9pS17tEWgl6Yfq7LfA5X5HxadBmban05zRB/GGIHxxh6g/ubEjokF9s44yQQEoKhVVsHHftjcr0PyVsFUS3VS2/7eimRO2TRRWeHzHJP+Pat2/t67Momn3kqQWpi/r/Bi21+DJKRiytFDUypyRGKThAy/4568YONOanwPKYC7D1xS8jsS2O7gBn4Tbehm90VGqb27DKp55XTHZYatOy91itC6CxDG1o15jnCnQ6HX6pg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque
