---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgDKijGeAz00gKWKE4bXIo0gKnIeqz6ZfeeY6BqaLvr02Ru1kQNXMSDB9tYbZDYpbyro85T6SXFoecOf39f29eD0mUB8L8ajkvsSSKdficZOmjr/dowG8+DF9VmQAMjrB2DOfkdcvof4pscmW/RKU/9pKgmw4K3DSQVhX5/HsYXc9euODyiokwsEIuyTCrVQyIgJAoXafGBOpZu5totLuvfff8kJNgG80M38xPzhoNKTKFmn3jr4FORTR78ItYl9zuYOMLDtAZXUS/Z8BVZoFsU3RxebDpB/0iV51ccCpmDDUYSM9ZSoHJ4gDTb+u7rlR7SlzusScGuspi4Fpp05xZO78Acm19uCgqTYjhPYxG/Fg8V/eLJGALcvSYz4hT31rQ16oLpdgx1pRfUMMemFsuPMlnp1Zzq8xhGG2qRZQXpZYEbNMRF7YnWoCxWpG72/IkDF+PiS/yLy+ybrpJfEzmWwBk1fVyHmt6bypi5LApo4n/C7f2YOdf04axcyM+G7pfuMk9niHDdglj18T5YyqzIa4M3+q2dP3Wjwt95z8YIijGovaI4qz2KeCvzl+t5hCIeThMyoDx0ov9/nN40k6EXeebZaPzE0D1dZ9i3mf2/v7yhXDjGYUVnD2BJm9QGw6fQbN4kYJlcLT9j47mlZuL3zn0sIKtdP4SKljrI8vGhYZAOZ/l1fyu2vfleOaD6cek5lIGW9s/K2Sk1K9ST8lV6aNRGjfdFrmFvNsLQ=
    username: AgAgVwxKbT6eVti2YpWgKBW8Nmazu2Gyf1pLoRXdmJW0GdcSqFJyrchxOx9aUoFpRqwHFeyAU+eGfQxX8NqrJS9rsOP57L1nBnJtZV8ryCAhqxHt8X9hh+eppTL6G5j5gAGkNysEpb7g8+PlAleYIHpEKvWsOQPUQns9/YAMHKLotRui6J5pEuHIkWDNagX5F1Ql3Yj9mBOLKMSSohtPsa98kbx8LaBgVAv6zm2ngRZ6QJJdmlP/0YTrK8owTB1+EzYqpUNCwNejRyqJnHFkF/UrlsjTWcuOIe4+nknwwzsP3Io6yd25qtvMbYhN9gb00IC5c0dm7/Ooxa+dKovFVJGFBz2Wn8zvMcce8g/Lh1ykSUjTCaa5+o/mT+yPzCF/8ZjuLea2L2NIreAtRwYK7MNpiC7xJ8T/fUHeh2LyjRk7tXs/XkaYAYLOx8mskhFEh732GSpFo1otqwQ0KbtJCgWuhVf96ScF0HBSghnOQpaaYrP/ootCT+KUPb+nroVZsD5NIpLuNaoHq7xehfWMoNkIhpmJLg4LMWHDeVSUMlwmreyQVkzvhXsan3HDio3mQuqC//aRDMAXYqCBrJ9rso5ySmzeaJ/xIGBi+DsSNBecDHgjqO0NrnscGWwDVLkILE6sdUNpZh4VsEoYgfSLxtf9DjTYe6InG0TeOLDWG+iGHyYlMWhaQzTQPNhzMCi00Y2HsQYd6Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque
