---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAmbjsW/Xzj/32T0Z+3JM8u/vpA2RLNca07srGrGohOpB2b6FuFX+G8Cd5vyloZflTyrVGnea0b+pe68aOtpW/8EAAPysAeFpsDla3uPqBVooKbQoO9LD1x7daC1vwz1zw9Tiz+HasM9GqgFifaF+/TeWfMDkZAe6AD5XyQMmvWvlzDQYFoBqGHhceiFeCvGNZSNfSwtrX+OiHWuXMhWcYpk45Otoh+n1KfZsv6lP1IKpCMoX++YH/6+dP2+fLFoiEl3loqGsUeXeSQjikz5cMog/7aM5eRhKmO3zS0IZv+NtifG6kftrARx8oViw4skMfAh1ACM0LeHleVC5whPAwFAcZuRsgeqKaVxbNzMqXaipKaqo0OexE/6Hd1F0br/iakyMudf6d68OahPlD6wysTOPgKPc5cDPoh/XTmqdDDTWMlO8Ei5W9AIQDQl3dBaIIshxuKygJJ6UJ1Ij7kVnT5+qlvIh1ixrWljuoEvZhHL+IleKKwi16c9OyEJbWT1xm78ok7/shHpw+rVZCE7R+CqDiAaKC8VyOAXAjPbj59m44mtADx3NxwlM51cAXIYx092MqRXIf84cOTFLpeEfQQBrc9uAXHbxirDlH+idK95IUH7xUYIPiqGh6TlEmZ3Rc4w8cTqDCYvcXkmzEutzbfNeOwFqgQql9nKDEba+OzfGzF7kEd1mdnOuuKcKRLFs7WLZSeBp95C+6h1JOKbpHNHYqKrGppVVzBuK0=
    username: AgBlMkE+xbUXcu6DdQUTflpNeHklYJ7V4Q+x9+QyxCcYx5FS8DaYHCRihsy1+FgQ+H7a4nzkVKBQCDwkNmnjLMwnuk3XuXUWSimaYlgkklrjIwJl6fhPBkMorUKVzc/du1ALA1uSsc0FwQCVRpeC353A+MAp+yHDL+PS7fHhC4QxBl63o0psEYWuimY1JDqciY7R8PoQJOGT0dhIzltsGMGiGpz5qQWQIXhu9Dg83E7rTAA0kkcSJu9pJ7wMPSud6jUoEyr8cU8kN9V1O6MgoVw7l/4G+TDxDCQFWOSutOC2xJ7GRqKhlWsgpfQTJVCI7qNnD8K4k1K9UmHt+PEZaMHUdeYzM178CwGZssF6gRWR9HgTfNERyY/yaK7QSDrcwxtWAHaELYLAiUU57jRXFMfTZSJ7Tjlw/GC8VGQGiz8RXKX0BHn/27RzO5gLyVQGvVzy+87wPcDKErdxBE/EDmtDt7zPVInvHzlrgUoJm1lgTc8k1FPz4wi3IGikVOdDfXfw60wM/MRrYyDjHhpTzWDXbBgOxDxPeZebTzE/DOhNbLGLdmh8pFmcW4G8SVQRQ7EIXYuzbisZsqi5hOHyJXEftiQhzZh247uvTnerVb2JgV2FlXKCwVwmDKJnmuib/GqSm7M3vDKCzHbeqfkoWANoN3uVFiE1WlvyaD1HLc+40WnvC58bb68FaE26pr1DPb+quBzR5A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque
