---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oidc-clients
  namespace: default
spec:
  encryptedData:
    aq.oidc.client.secret: AgC58+RsvbSQz5ideLG+x7hNozMHFz4kSjnfA6nOEbpcRlTlb2OV7Q6aesrLENkAa7axRIOrvfw3uctEASkGJ6s464iZhjFZDsHWRPvVgpI3iMmcRzGz79sAmkZQRWPZZbwbqD7Bl5ZCPN3VpGIkVMZhvq+lGZ4pdIDjGRdawgS4LpH6PVzISMIYQXDP/dC7V04tLmJRRqR4RxPxvZv17mt1Y4AyQLfE8r8tczk3vWKhToh/uUtyys/aw/awt5KgLHAF2qnaB/75w/z7PyPgIp0mbCt5MCIH2vanmKbiz1HBM6hY9M2Cc+8wwjGIELMkyvnlh8JXuJtw5aA9F2HlRBFlljGKsSE+HCXQ07whBiavY9gSnyf8LcWkxMITJjmmSig8bFLNYpUZe/qQK0w1Q+z71eUxtLXMyhjKKsN8sS2+mvJKqWURPAjHbu5hrmgEDRQN+PpmkLYmlvqhfrm8CBuk0vfwmU3Q9GBV/TrYaCigMZnntOoyrJjLPywcq0WIFGVNlgSIfyHUtASIBCUL1RK0PbMDTINoQp4t8Rz7ECEeDAzlEg/MSY99fSHz/D1TVsOjRJ0WbSjLzzKYHpUfzXpnzoGLvFDexyw9hke468gLWeK4L8XpSG8KpZgQGJViF5YwpHmVchdb5cmslwc6MSONT5Io9sum124VeWf1hKtozS5rUsnKhfGtl0wMv+ZmUew3SnC4Zs71k6SnUuO44M5GG0auLmaL5mLvNErp7LlllZy/sczUYvd5NI3lFYipCxvH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: oidc-clients
      namespace: default
    type: Opaque
